### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by Rexadev** [xr18b/myPrivacyDNS#1]

**Comment by xr18b** [comment]
Hello,
It is not related to this, no.
I manage a bunch of personal DNS servers (at home, at work, ...) that I use to block a bunch of websites (mostly tracking and privacy invasive domains). At some point, I created a script to automate the generation of the configuration files to ease the management of the different servers I manage.
This repository hosts this script for anyone to reuse as they will.

**Comment by Rexadev** [comment]
@xr18b you should rename it

**Comment by xr18b** [comment]
I don't see any issue with my repository's name

**Comment by xr18b** [comment]
@Rexadev: For transparency reason, please avoid deleting your messages and renaming the issue to 'Deleted'
